package com.hokori.web.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.util.List;
import java.util.Map;

/**
 * Request DTO for responding in a conversation practice session
 * FE maintains conversation history and sends it with each request
 */
@Schema(description = "Request for responding in a conversation practice session")
public class ConversationRespondRequest {
    
    @NotBlank(message = "Conversation ID is required")
    @Schema(description = "Temporary conversation ID (generated by FE)", 
            example = "conv-abc123", 
            required = true)
    private String conversationId; // Temporary ID, not stored in DB
    
    @NotNull(message = "Conversation history is required")
    @Schema(description = "Full conversation history maintained by FE", 
            example = "[{\"role\":\"ai\",\"text\":\"こんにちは\",\"textVi\":\"Xin chào\"},{\"role\":\"user\",\"text\":\"こんにちは\",\"textVi\":\"Xin chào\"}]", 
            required = true)
    private List<Map<String, String>> conversationHistory; // Full history from FE
    
    @NotBlank(message = "Audio data is required")
    @Size(max = 10485760, message = "Audio data must not exceed 10MB")
    @Schema(description = "Base64 encoded audio of user's response", 
            example = "UklGRiQAAABXQVZFZm10IBAAAAABAAEAQB8AAEAfAAABAAgAZGF0YQAAAAA=", 
            required = true)
    private String audioData; // Base64 encoded audio
    
    @Schema(description = "Audio format", 
            example = "wav", 
            allowableValues = {"wav", "mp3", "flac", "ogg", "webm"}, 
            defaultValue = "wav")
    private String audioFormat; // Optional, default "wav"
    
    @Schema(description = "Language code", 
            example = "ja-JP", 
            allowableValues = {"ja-JP"}, 
            defaultValue = "ja-JP")
    private String language; // Optional, default "ja-JP"
    
    @Schema(description = "JLPT level", 
            example = "N5", 
            allowableValues = {"N5", "N4", "N3", "N2", "N1"})
    private String level; // JLPT level
    
    @Schema(description = "Conversation scenario", 
            example = "restaurant")
    private String scenario; // Conversation scenario
    
    public ConversationRespondRequest() {}
    
    public String getConversationId() {
        return conversationId;
    }
    
    public void setConversationId(String conversationId) {
        this.conversationId = conversationId;
    }
    
    public List<Map<String, String>> getConversationHistory() {
        return conversationHistory;
    }
    
    public void setConversationHistory(List<Map<String, String>> conversationHistory) {
        this.conversationHistory = conversationHistory;
    }
    
    public String getAudioData() {
        return audioData;
    }
    
    public void setAudioData(String audioData) {
        this.audioData = audioData;
    }
    
    public String getAudioFormat() {
        return audioFormat;
    }
    
    public void setAudioFormat(String audioFormat) {
        this.audioFormat = audioFormat;
    }
    
    public String getLanguage() {
        return language;
    }
    
    public void setLanguage(String language) {
        this.language = language;
    }
    
    public String getLevel() {
        return level;
    }
    
    public void setLevel(String level) {
        this.level = level;
    }
    
    public String getScenario() {
        return scenario;
    }
    
    public void setScenario(String scenario) {
        this.scenario = scenario;
    }
    
    public boolean isValidAudioFormat() {
        return audioFormat == null || 
               audioFormat.equals("wav") || 
               audioFormat.equals("mp3") || 
               audioFormat.equals("flac") || 
               audioFormat.equals("ogg") ||
               audioFormat.equals("webm");
    }
}

